apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- hook-configmap.yaml
- hook-server.yaml
- decoratorcontroller.yaml
- sandmand-monitor.yaml
- sandman-dashboard.yaml
